"""empty message

Revision ID: 796a97591070
Revises: 40e8c5cd2d60
Create Date: 2021-03-18 20:22:32.646000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796a97591070'
down_revision = '40e8c5cd2d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_bathrooms_key', 'property', type_='unique')
    op.drop_constraint('property_description_key', 'property', type_='unique')
    op.drop_constraint('property_location_key', 'property', type_='unique')
    op.drop_constraint('property_price_key', 'property', type_='unique')
    op.drop_constraint('property_propery_type_key', 'property', type_='unique')
    op.drop_constraint('property_rooms_key', 'property', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('property_rooms_key', 'property', ['rooms'])
    op.create_unique_constraint('property_propery_type_key', 'property', ['propery_type'])
    op.create_unique_constraint('property_price_key', 'property', ['price'])
    op.create_unique_constraint('property_location_key', 'property', ['location'])
    op.create_unique_constraint('property_description_key', 'property', ['description'])
    op.create_unique_constraint('property_bathrooms_key', 'property', ['bathrooms'])
    # ### end Alembic commands ###
